### ISSUE TITLE
`generate-all-protocols` error

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-aea#277]
**Describe the bug**
Problem with generate all command.

**To Reproduce**
Go to `https://github.com/valory-xyz/agent-academy-1/blob/main/tox.ini#L210` and run `tox -e check-generate-all-protocols`

**Expected behavior**
Just works.

**Screenshots**
```
Calling command ('/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/bin/python', '-m', 'aea.cli', 'create', '--local', '--empty', 'my_aea', '--author', 'fetchai') with kwargs {}
    _     _____     _    
   / \   | ____|   / \   
  / _ \  |  _|    / _ \  
 / ___ \ | |___  / ___ \ 
/_/   \_\|_____|/_/   \_\
                         
v1.16.0

AEA configurations already initialized: {'author': 'valory'}. To reset use '--reset'.
Initializing AEA project 'my_aea'
Creating project directory './my_aea'
Creating config file aea-config.yaml
====================================================================================================
[2022-08-21 17:46:25,664][INFO] Processing protocol at path /Users/davidminarsch/v_projects/agent-academy-1/packages/open_aea/protocols/signing
Traceback (most recent call last):
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/bin/aea", line 8, in <module>
    sys.exit(cli())
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/aea/cli/generate_all_protocols.py", line 465, in generate_all_protocols
    _process_packages_protocol(
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/aea/cli/generate_all_protocols.py", line 381, in _process_packages_protocol
    old_protocol_generator_docstring = _parse_generator_docstring(package_path)
  File "/Users/davidminarsch/.local/share/virtualenvs/agent-academy-1-GRcsCzDq/lib/python3.8/site-packages/aea/cli/generate_all_protocols.py", line 215, in _parse_generator_docstring
    raise ValueError("protocol generator docstring not found")
ValueError: protocol generator docstring not found
```

**Comment by angrybayblade** [comment]
Fixed here https://github.com/valory-xyz/open-aea/pull/287
